version: "3"
services:
  rabbitmq:
    image: rabbitmq:3-management
    hostname: 'rabbitmq'
    volumes:
      - ./rabbitmq.conf:/etc/rabbitmq/conf.d/11-custom.conf
    ports:
      - 15672:15672
      - 5672:5672

  architectureManager-frontend:
    image: node:latest
    entrypoint: npm start
    working_dir: /app
    ports:
      - 3002:3002
    volumes:
      - ./blocks/architectureManager/frontend:/app
    environment:
      PORT: 3002

  architectureManager:
    image: node:latest
    entrypoint: npm run dev
    working_dir: /app
    ports:
      - 3001:80
    volumes:
      - ./blocks/architectureManager/:/app
      - ./libs:/app/node_modules/@amicopo
    environment:
      PORT: 80
      NODE_ENV: development
      IOConfig: '{ "endpoint": "amqp://rabbitmq" }'
      DEBUG: architectureManager
      DEBUG_COLORS: true

  gateway:
    image: node:latest
    entrypoint: npm run dev
    working_dir: /app
    ports:
      - 3000:3000
    volumes:
      - ./blocks/gateway/:/app
      - ./libs:/app/node_modules/@amicopo
    environment:
      IOConfig: '{ "archEndpoint": "amqp://rabbitmq", "archExchange": "arch-management-gateway" }'
      DEBUG: 'gateway:*'
      DEBUG_COLORS: true

  mongodb:
    image: node:latest
    entrypoint: npm run dev
    working_dir: /app
    volumes:
      - ./blocks/mongodb/:/app
      - ./libs:/app/node_modules/@amicopo
    environment:
      IOConfig: '{ "archEndpoint": "amqp://rabbitmq", "archExchange": "arch-management-mongodb" }'
      DEBUG: 'mongodb:*'
      DEBUG_COLORS: true

  filesystem:
    image: node:latest
    entrypoint: npm run dev
    working_dir: /app
    volumes:
      - ./blocks/filesystem/:/app
      - ./libs:/app/node_modules/@amicopo
    environment:
      IOConfig: '{ "archEndpoint": "amqp://rabbitmq", "archExchange": "arch-management-filesystem" }'
      DEBUG: ''
      DEBUG_COLORS: true

  util:
    image: node:latest
    entrypoint: npm run dev
    working_dir: /app
    volumes:
      - ./blocks/util/:/app
      - ./libs:/app/node_modules/@amicopo
    environment:
      IOConfig: '{ "archEndpoint": "amqp://rabbitmq", "archExchange": "arch-management-util" }'
      DEBUG: ''
      DEBUG_COLORS: true

  dataset-mongodb:
    image: mongo
    command: mongod --quiet --logpath /dev/null
    ports:
      - 27017:27017
