version: "3"
services:
  rabbitmq:
    image: rabbitmq:3-management
    hostname: 'rabbitmq'
    volumes:
      - ./rabbitmq.conf:/etc/rabbitmq/conf.d/11-custom.conf
    ports:
      - 15672:15672
      - 5672:5672

  architectureManager:
    image: node:latest
    entrypoint: npm run dev
    working_dir: /app
    ports:
      - 3001:80
    volumes:
      - ./blocks/architectureManager/:/app
      - ./libs:/app/node_modules/@amicopo
    environment:
      PORT: 80
      IOConfig: '{ "endpoint": "amqp://rabbitmq" }'
      DEBUG: architectureManager, messaging
      DEBUG_COLORS: true

  gateway:
    image: node:latest
    entrypoint: npm run dev
    working_dir: /app
    ports:
      - 3000:3000
    volumes:
      - ./blocks/gateway/:/app
      - ./libs:/app/node_modules/@amicopo
    environment:
      IOConfig: '{ "archEndpoint": "amqp://rabbitmq", "archExchange": "arch-management-gateway" }'
      DEBUG: 'gateway:*,messaging'
      DEBUG_COLORS: true

  filesystem:
    image: node:latest
    entrypoint: npm run dev
    working_dir: /app
    volumes:
      - ./blocks/filesystem/:/app
      - ./libs:/app/node_modules/@amicopo
    environment:
      IOConfig: '{ "archEndpoint": "amqp://rabbitmq", "archExchange": "arch-management-filesystem" }'
      DEBUG: 'messaging'
      DEBUG_COLORS: true

  util:
    image: node:latest
    entrypoint: npm run dev
    working_dir: /app
    volumes:
      - ./blocks/util/:/app
      - ./libs:/app/node_modules/@amicopo
    environment:
      IOConfig: '{ "archEndpoint": "amqp://rabbitmq", "archExchange": "arch-management-util" }'
      DEBUG: 'messaging'
      DEBUG_COLORS: true
