version: "3"
services:
  rabbitmq:
    image: rabbitmq:3-management
    hostname: 'rabbitmq'
    volumes:
      - ./rabbitmq.conf:/etc/rabbitmq/conf.d/11-custom.conf
    ports:
      - 15672:15672

  gateway:
    build:
      context: blocks/gateway
      args:
        NODE_ENV: development
    entrypoint: npm run dev
    ports:
      - 3000:3000
    volumes:
      - ./blocks/gateway/:/app
      - ./libs:/libs
    environment:
      IOConfig: '[{"endpoint":"amqp://rabbitmq","queues":{"!gateway":{"steps":{"1":{"fnName":"reply","extraArgs":[]}}}}}]'
      QUEUE_ID: 0
      QUEUE_NAME: 'plusCalculation'
      DEBUG: 'gateway:*'

  plus:
    build:
      context: blocks/plus
      args:
        NODE_ENV: development
    entrypoint: npm run dev
    volumes:
      - ./blocks/plus/:/app
      - ./libs:/libs
    environment:
      IOConfig: '[{"endpoint":"amqp://rabbitmq","queues":{"plusCalculation":{"steps":{"0":{"fnName":"plus","extraArgs":[2],"outId":0,"outQueue":"!gateway"}}}}}]'
