version: "3"
services:
  rabbitmq:
    image: rabbitmq:3-management
    hostname: 'rabbitmq'
    volumes:
      - ./rabbitmq.conf:/etc/rabbitmq/conf.d/11-custom.conf
    ports:
      - 15672:15672
      - 5672:5672

  gateway:
    image: node:latest
    entrypoint: npm run dev
    working_dir: /app
    ports:
      - 3000:3000
    volumes:
      - ./blocks/gateway/:/app
      - ./libs:/libs
    environment:
      IOConfig: '{ "archEndpoint": "amqp://rabbitmq", "archExchange": "arch-management-gateway" }'
      DEBUG: 'gateway:*,messaging'

  min:
    image: node:latest
    entrypoint: npm run dev
    working_dir: /app
    volumes:
      - ./blocks/min/:/app
      - ./libs:/libs
    environment:
      IOConfig: '{ "archEndpoint": "amqp://rabbitmq", "archExchange": "arch-management-min" }'
      DEBUG: 'messaging'

  mod:
    image: node:latest
    entrypoint: npm run dev
    working_dir: /app
    volumes:
      - ./blocks/mod/:/app
      - ./libs:/libs
    environment:
      IOConfig: '{ "archEndpoint": "amqp://rabbitmq", "archExchange": "arch-management-mod" }'
      DEBUG: 'messaging'

  mul:
    image: node:latest
    entrypoint: npm run dev
    working_dir: /app
    volumes:
      - ./blocks/mul/:/app
      - ./libs:/libs
    environment:
      IOConfig: '{ "archEndpoint": "amqp://rabbitmq", "archExchange": "arch-management-mul" }'
      DEBUG: 'messaging'

  plus:
    image: node:latest
    entrypoint: npm run dev
    working_dir: /app
    volumes:
      - ./blocks/plus/:/app
      - ./libs:/libs
    environment:
      IOConfig: '{ "archEndpoint": "amqp://rabbitmq", "archExchange": "arch-management-plus" }'
      DEBUG: 'messaging'
