version: '3'

services:
  traefik:
    image: traefik:latest
    container_name: traefik
    restart: unless-stopped
    command:
    - --api.insecure=true
    - --providers.docker=true
    - --providers.docker.exposedbydefault=false
    - --providers.docker.network=traefik
    - --entrypoints.web.address=:80

    environment:
      - TZ=Europe/Amsterdam

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

    ports:
    - "80:80"
    - "8080:8080"
    networks:
      - traefik

networks:
  traefik:
    name: traefik
